// <auto-generated />
using System;
using Consultorio.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consultorio.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Consultorio.Core.Modelos.Cliente", b =>
                {
                    b.Property<long>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CEP")
                        .HasMaxLength(9)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CPF")
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CarteiraPlanoSaude")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("CodigoPlanoSaude")
                        .HasColumnType("MEDIUMINT");

                    b.Property<DateOnly>("DataCadastro")
                        .HasColumnType("Date");

                    b.Property<DateOnly?>("DataNasc")
                        .HasColumnType("Date");

                    b.Property<string>("Empresa")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Endereco")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1024)
                        .HasColumnType("MEDIUMTEXT");

                    b.Property<string>("Referencia")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ResponsavelLegal")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UF")
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Codigo");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Consultorio.Core.Modelos.EmailCliente", b =>
                {
                    b.Property<long>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("MEDIUMINT");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Codigo");

                    b.ToTable("EmailCliente", (string)null);
                });

            modelBuilder.Entity("Consultorio.Core.Modelos.PlanoSaude", b =>
                {
                    b.Property<long>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("MEDIUMTEXT");

                    b.HasKey("Codigo");

                    b.ToTable("PlanosSaude", (string)null);
                });

            modelBuilder.Entity("Consultorio.Core.Modelos.TelefoneCliente", b =>
                {
                    b.Property<long>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("MEDIUMINT");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Codigo");

                    b.ToTable("TelefoneCliente", (string)null);
                });

            modelBuilder.Entity("Consultorio.Core.Modelos.TelefonePlanoSaude", b =>
                {
                    b.Property<long>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("CodigoPlano")
                        .HasColumnType("MEDIUMINT");

                    b.Property<sbyte?>("DDD")
                        .HasMaxLength(2)
                        .HasColumnType("TINYINT");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Codigo");

                    b.ToTable("TelefonePlanoSaude", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
